language: python
group: travis_latest

# Root level OS + distro required
os: linux
dist: xenial

python:
- "3.8.1"

jobs:
  include:
  - os: linux
  - os: osx
    osx_image: xcode12.5
    language: shell
    install: pip3 install -r requirements.txt
  - os: windows
    language: shell
    
    before_install:
    - choco install python3 --version=3.8.1
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

install: pip install -r requirements.txt

script: 
  - pytest
  # build
  - pyinstaller --onefile --name autor1 src/__main__.py
  # Copy test projects into build folder
  - cp ./Projects/*.dbpr ./dist/
  - cd ./dist
  - ls -la
  # Run executable with test projects. Expect a failure due to an uninitialized file
  - if [ $TRAVIS_OS_NAME=="windows" ]; then echo | (! ./start-windows.bat); fi
  - if [ $TRAVIS_OS_NAME=="osx" ]; then echo | (! ./start-macos.command); fi
  - if [ $TRAVIS_OS_NAME=="linux" ]; then ! ./autor1 ./; fi
  # Print most recent log
  - cat ./LOGS/"$(ls -rt ./LOGS | tail -n1)"
  - ls ./*_AUTO.dbpr
  # Remove uninitialized file
  - rm ./*no_init.dbpr
  # Re-run executable with tests. This should pass without failure now.
  - if [ $TRAVIS_OS_NAME=="windows" ]; then echo | ./start-windows.bat; fi
  - if [ $TRAVIS_OS_NAME=="osx" ]; then echo | ./start-macos.command; fi
  - if [ $TRAVIS_OS_NAME=="linux" ]; then ./autor1 ./; fi
  - cat ./LOGS/"$(ls -rt ./LOGS | tail -n1)"
  - ls ./*_AUTO.dbpr
  # Remove generated files to prepare for zipping + release later
  - rm *.dbpr
  - rm -r ./LOGS
  - cd ../

before_deploy:
  - cp LICENSE ./dist
  - cp ./README.md ./dist
  - if [ $TRAVIS_OS_NAME == "windows" ]; then rm ./dist/start-macos.command; fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then rm ./dist/start-windows.bat; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then rm ./dist/start-windows.bat && rm ./dist/start-macos.command; fi
  - mv ./dist $RELEASE_NAME
  - tar -a -c -f $RELEASE_NAME.zip ./$RELEASE_NAME/

deploy:
  provider: releases
  token: $GH_TOKEN
  file_glob: true
  overwrite: true
  file: 
    - $RELEASE_NAME.zip
  draft: true
  name: $TRAVIS_TAG (DRAFT)
  on:
    tags: true
    
env:
  global:
    - RELEASE_NAME="AUTOR1-$TRAVIS_TAG-$TRAVIS_OS_NAME"
    - secure: A8sQELollcIcNx36trQBLaZqQ6KBYeOcSs3Zxc3W86PYt/GWCUlDUYi7uxYDz5sbCyT2PkiJu2d85XlNNdnIWunsZsg7R2FaY401qZ0NUbYceNH+OvhbyVyIeMRulUisz6dRDGl6lf1Xge6tZrXKMSSGXECr0oAcIREGJPL5NOGPCpIzZcPbuXMJC7eBM+jZfihX2J1jmRe3/OpwLsfTxXkBtUhU7+3GY4W8k6844zflO8WaU7Ik1cAqP21KfUXkO5LuqL0MMSjCGweKF7TPU6qKajIGc0yWiZlG2293VE7R7lLiqBIPnFCs5fe2InUaHJvj1vf5CDUsCSBPcHF07sUt3cPRKpAsd3SRbBrt59/BStohwmnOEZjNKGykpttMJK5Wcot6a3hYsXeEKZrl6z1kr82KvBQjrPQEmkRADJPHhQyk2T+cgpVyMN9V+MZAxtJhR6JANv5d8IiDVB9ZF306sRdqczRwzZOTGEyo+V4OqdViVztPUozS8Uo9muueC0hcijCrp4f3VqtxxSp65hkQNthh5aHb7x+stiiTn22ALe0X4jqCjypM8zc7pxvcO0uulXNb1bfmaD9uImtgyYOcRlmTyIkWsBHHEkk6cuWJ+l1rHSiBusRaXJl/+IrqCjkNxOzuqmHuH6Ota2XUJo4rixoAhle3v8ofVmTreJs=
